version: "3"
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    volumes:
      - .:/jimoshare
      - public_data:/jimoshare/public
      - tmp_data:/jimoshare/tmp
      - log_data:/jimoshare/log
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./Docker/db/Dockerfile
    image: postgres
    container_name: postgresql
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      # - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    hostname: postgres
    restart: always
    user: root
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - public_data:/jimoshare/public
      - tmp_data:/jimoshare/tmp
    ports:
      - 80:80
    depends_on:
      - app

  # pgadmin4:
  #   image: dpage/pgadmin4:3.3
  #   container_name: pgadmin4
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin/storage
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   hostname: pgadmin4
  #   restart: always
  #   depends_on:
  #     - db
