# version: '3'
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/jimoshare
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       # - chrome
#     stdin_open: true
#     tty: true
#   chrome:
#     image: selenium/standalone-chrome:3.141.59-dubnium
#     ports:
#       - 4444:4444

version: '3'
volumes:
  postgres_data:
  public_data:
  tmp_data:
  log_data:
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/jimoshare
      - public_data:/jimoshare/public
      - tmp_data:/jimoshare/tmp
      - log_data:/jimoshare/log
    depends_on:
      - db
  db:
    build:
      # image: postgres:12.3
      context: .
      dockerfile: ./Docker/db/Dockerfile
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'
      # POSTGRES_HOST_AUTH_METHOD: trust
      # - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - public_data:/jimoshare/public
      - tmp_data:/jimoshare/tmp
    ports:
      - 80:80
    depends_on:
      - app