# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: app_test
    working_directory: ~/jimoshare
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: root
    working_directory: ~/jimoshare
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

# workflows:
#   version: 2.1
#   rubocop_rspec:
#     jobs:
#       - rubocop
#       - rspec:
#           requires:
#             - rubocop

# jobs:
  # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
  build:
      docker:
          - image: alpine
      steps:
          - checkout
          - run:
              name: Echo Test
              command: echo "CircleCI Test"
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
      machine:
          image: circleci/classic:edge
      steps:
          - checkout
          # CircleCI に登録した秘密鍵を呼び出す
          - add_ssh_keys:
          # CircleCI に登録した環境変数を使って SSH
          - run: ssh ${USER_NAME}@${HOST_NAME} 'cd [jimoshare] && git pull'

workflows:
    version: 2.1
    rubocop_rspec:
      jobs:
        - rubocop
        - rspec:
            requires:
              - rubocop
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    build_and_deploy:
        # build ジョブと deploy ジョブを呼び出す
        jobs:
            - build
            - deploy:
                requires:
                    # deploy ジョブより先に build ジョブを実行しろ！
                    - build
                # master ブランチに push された場合のみ deploy ジョブを実行する
                filters:
                    branches:
                        only: master
  # build-and-deploy:
  #   jobs:
  #     - aws-ecr/build_and_push_image:
  #         account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}
  #         .amazonaws.com"
  #         repo: "${AWS_RESOURCE_NAME_PREFIX}"
  #         region: ${AWS_DEFAULT_REGION}
  #         tag: "${CIRCLE_SHA1}"



# version: 2.1
# orbs:
#   aws-ecr: circleci/aws-ecr@6.7.0
#   aws-ecs: circleci/aws-ecs@1.1.0
#   workflows:
#     # Nginxのデプロイ
#     nginx-deploy:
#     jobs:
#       - aws-ecr/build-and-push-image:
#         account-url: AWS_ECR_ACCOUNT_URL
#         region: AWS_REGION
#         aws-access-key-id: AWS_ACCESS_KEY_ID
#         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
#         create-repo: true
#         dockerfile: ./docker/nginx/Dockerfile
#         repo: nginx
#         tag: "${CIRCLE_SHA1}"
#         filters:
#           branches:
#             only: master
#       - aws-ecs/deploy-service-update:
#         requires:
#           - aws-ecr/build-and-push-image
#           family: 'nginx-rails-app' # ECSのタスク定義名
  #         cluster-name: '${ECS_ARN}'  #ECSのクラスターのARN
  # #         service-name: 'test'  #サービス名
  #         container-image-name-updates: "container=nginx,tag=${CIRCLE_SHA1}"
  # # Railsのデプロイ
  # rails-deploy:
  #   jobs:
  #     - aws-ecr/build-and-push-image:
  #         account-url: AWS_ECR_ACCOUNT_URL
  #         region: AWS_REGION
  #         aws-access-key-id: AWS_ACCESS_KEY_ID
  #         aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  #         create-repo: true
  #         dockerfile: ./docker/rails/Dockerfile
  #         repo: rails
  #         tag: "${CIRCLE_SHA1}"
  #         filters:
  #           branches:
  #             only: master
  #     - aws-ecs/deploy-service-update:
  #         requires:
  #           - aws-ecr/build-and-push-image
  #         family: 'nginx-rails-app' # ECSのタスク定義名
  #         cluster-name: '${ECS_ARN}' #ECSのクラスターのARN
  #         service-name: 'test' #サービス名
  #         container-image-name-updates: "container=rails,tag=${CIRCLE_SHA1}"
