# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: app_test
    working_directory: ~/jimoshare
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Rubocop
      - run:
          name: Rubocop
          command: bundle exec rubocop

  rspec:
    docker:
      - image: circleci/ruby:2.6.5-node-browsers-legacy
        environment:
          RAILS_ENV: test
          POSTGRES_HOST: 127.0.0.1
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: app_test
          POSTGRES_PASSWORD: root
    working_directory: ~/jimoshare
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # Rspec
      - run:
          name: Rspec
          command: bundle exec rspec

workflows:
  version: 2.1
  rubocop_rspec:
    jobs:
      - rubocop
      - rspec:
          requires:
            - rubocop
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ruge.e.azul@gmail.com
          aws-access-key-id:  AKIARO2HSNR3H4I2WLV7
          aws-secret-access-key: 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
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: ap-northeast-1
          repo: circleci-ecr-orb-demo
          tag: "$CIRCLE_SHA1"