default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: utf8
  username: root
  database: test_sample_db
  password:
  host: db
  port: 5432

development:
  <<: *default

test:
  <<: *default
